### ISSUE TITLE
improve `messageReferenceMatchers` DX

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#746] opened 2023-05-13 19:31 UTC
## Problem

The current way of declaring messageReferenceMatchers is really hard. People have to write 30 lines of very specific JS which also bloatens the config file doesn't feel nice.

like:

```js
messageReferenceMatchers: [
	async (/** @type {{ "documentText": string; }} */ args) => {
		const regex = /(?<!\w){?t\(['"](?<messageId>\S+)['"]\)}?/gm
		const str = args.documentText
		let match
		const result = []

		while ((match = regex.exec(str)) !== null) {
			const startLine =
				(str.slice(0, Math.max(0, match.index)).match(/\n/g) || []).length + 1
			const startPos = match.index - str.lastIndexOf("\n", match.index - 1)
			const endPos =
				match.index +
				match[0].length -
				str.lastIndexOf("\n", match.index + match[0].length - 1)
			const endLine =
				(str.slice(0, Math.max(0, match.index + match[0].length)).match(/\n/g) || [])
					.length + 1

			if (match.groups && "messageId" in match.groups) {
				result.push({
					messageId: match.groups["messageId"],
					position: {
						start: {
							line: startLine,
							character: startPos,
						},
						end: {
							line: endLine,
							character: endPos,
						},
					},
				})
			}
		}
		return result
	},
],
```

## Proposal

Come up with a shorter version of the same functionality, like only rely on a regex and establish a standard behavior on how to match the position.

## Outcome

Easier install & setup of the solution, therefore higher adoption.

**Comment by samuelstroschein** [comment] 2023-05-14 14:14
_This issue is a duplicate of https://github.com/inlang/inlang/discussions/381. I am closing the discussion in favor of this issue._ 

The matcher API is correct and should not be changed. What we should do is recommend a parser. From #381: 

> [Chevrotain](https://chevrotain.io/docs/) does indeed look really promising.
> 
> * everything in JavaScript makes building grammars easier
> * no parser generator required, increases the DX
> * fast

---

> Come up with a shorter version of the same functionality, like only rely on a regex and establish a standard behavior on how to match the position. 

No no no no no no no absolutely no regex should be recommended. Regex completely crashes on matching source code patterns. Large chunks of bugs in i18n ally are due to regex being abused to parse source code.  

> People have to write 30 lines of very specific JS which also bloatens the config file doesn't feel nice.

Keep in mind that such functionality is provided by plugins. Users are not expected to write matchers themselves. Thus, the matcher API doesn't bloat the config.

**Comment by felixhaeberle** [comment] 2023-05-14 14:46
@samuelstroschein I understand your points. The regex suggestion was indeed thought with a recommended parser in mind.

**Comment by samuelstroschein** [comment] 2023-06-05 12:19
Will be solved by https://github.com/inlang/plugin-i18next/pull/3. Thus closing this as "one plugin uses a reference implementation with a proper parser."

**Closed by samuelstroschein** 2023-06-05 12:19 UTC
Labels: type: improvement, effort: medium, scope: ide-extension
