### ISSUE TITLE
Switch to esbuild for typescript transpilation in svelte ast transform

### ISSUE THREAD

**Issue by benjaminpreiss** [inlang/inlang#614] opened 2023-05-02 03:03 UTC
We are using `preprocess()` from `svelte/compiler` to do AST insertions in svelte files. For that, we have to first transpile the typescript to be able to parse the svelte file to an AST.

The official docs for preprocess state, that [esbuild is a very performant way of doing so](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#overriding-preprocessors).

@ivanhofer What do you think? Currently, we are doing it like so: https://github.com/inlang/inlang/blob/8cbd81b0a79cb348b29fe338c272f05c4fb2cd9d/source-code/sdk-js/src/adapter-sveltekit/ast-transformation/transforms/*.svelte.ts#L56

**Comment by benjaminpreiss** [comment] 2023-05-02 03:07
Bundlesize esbuild: https://bundlejs.com/?q=esbuild&treeshake=%5B%7BtransformSync%7D%5D&config=%7B%22analysis%22%3Aundefined%7D

Bundlesize vitePreprocess: https://bundlejs.com/?q=%40sveltejs%2Fvite-plugin-svelte&treeshake=%5B%7BvitePreprocess%7D%5D&config=%7B%22analysis%22%3Aundefined%7D

**Comment by ivanhofer** [comment] 2023-05-02 04:33
The problem is that we can't include esbuild in our bundle. Each project would need to add it to their dependencies. As far as I know we can include `vitePreprocess` in our bundle.
We can investigate this in the future.

**Comment by ivanhofer** [comment] 2023-06-06 18:30
closing as not planned

**Closed by ivanhofer** 2023-06-06 18:30 UTC
Labels: type: improvement, effort: low, scope: sdk-js
