### ISSUE TITLE
Conflict between 'inlang' and 'sass' libraries in SvelteKit causing error with nested styles

### ISSUE THREAD

**Issue by Devidence7** [inlang/inlang#792] opened 2023-05-18 17:54 UTC
## Problem
When using the inlang library in a SvelteKit project, there is a conflict with another library called sass. Specifically, when I have nested Sass styles in my code, it results in the following error:

```
[vite] Internal server error: Identifier is expected
  Plugin: vite-plugin-inlang-sdk-js-sveltekit
  File: <Omited>/src/routes/(web)/+layout.svelte:41:0
  34:     background-color: black;
  35:
  36:     .a {
          ^
  37:     }
  38:   }
  at error (file:///<Omited>/node_modules/.pnpm/svelte@3.59.1/node_modules/svelte/compiler.mjs:13207:19)
  at Parser$1.error (file:///<Omited>/node_modules/.pnpm/svelte@3.59.1/node_modules/svelte/compiler.mjs:13285:9)
  at Object.read_style [as read] (file:///<Omited>/node_modules/.pnpm/svelte@3.59.1/node_modules/svelte/compiler.mjs:9636:20)
  at tag (file:///<Omited>/node_modules/.pnpm/svelte@3.59.1/node_modules/svelte/compiler.mjs:12231:33)
  at new Parser$1 (file:///<Omited>/node_modules/.pnpm/svelte@3.59.1/node_modules/svelte/compiler.mjs:13244:21)
  at parse$b (file:///<Omited>/node_modules/.pnpm/svelte@3.59.1/node_modules/svelte/compiler.mjs:13384:20)
  at ji (file:///<Omited>/node_modules/.pnpm/@inlang+sdk-js@0.4.5_@sveltejs+kit@1.18.0_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:229:7980)
  at async TransformContext.transform (file:///<Omited>/node_modules/.pnpm/@inlang+sdk-js@0.4.5_@sveltejs+kit@1.18.0_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:338:138)
  at async Object.transform (file:///<Omited>/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.0_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42919:30)
  at async loadAndTransform (file:///<Omited>/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.0_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53385:29)
```

### Expected behavior
I expect the inlang library to work properly even when using nested Sass styles.

## Steps to reproduce

1. Go to the 'inlang' repository.
2. Set up a SvelteKit project.
3. Import the inlang library and configure it.
4. Create a Svelte component that includes nested Sass styles.
5. Run the project and observe the error.

### Additional information (screenshots?)
N/A

**Comment by samuelstroschein** [comment] 2023-05-19 06:31
This is an issue for @ivanhofer or @benjaminpreiss. 

FYI @Devidence7, Ivan is on vacation for the next two weeks. Reply might be a bit slow. I hope that Benjamin can take over. Thanks for reporting the bug!

**Comment by ivanhofer** [comment] 2023-05-19 08:38
@Devidence7 thanks for opening this issue. I just have released version `0.6.0` which should fix the bug.

**Comment by Renkas** [comment] 2023-05-19 19:31
It's not fixed on 0.6.0 for me
```
10:28:52 PM [vite] Internal server error: Colon is expected
Plugin: vite-plugin-inlang-sdk-js-sveltekit
File: /<omited>/src/routes/+layout.svelte:16:7
12:       padding: 0 0 50px;
13:
14:       a {
    ^
    15:         color: red;
    16:       }
at error (file://<omited>/node_modules/svelte/compiler.mjs:13207:19)
at Parser$1.error (file://<omited>/node_modules/svelte/compiler.mjs:13285:9)
at Object.read_style [as read] (file://<omited>/node_modules/svelte/compiler.mjs:9636:20)
at tag (file://<omited>/node_modules/svelte/compiler.mjs:12231:33)
at new Parser$1 (file://<omited>/node_modules/svelte/compiler.mjs:13244:21)
at parse$b (file://<omited>/node_modules/svelte/compiler.mjs:13384:20)
at kT (file://<omited>/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:268:954)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async TransformContext.transform (file://<omited>/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:338:198)
at async Object.transform (file://<omited>/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42883:30)
```

```
<style lang="scss">
    main {
      padding: 0 0 50px;

      a {
        color: red;
      }
    }
</style>
```

**Comment by ivanhofer** [comment] 2023-05-21 16:39
@Renkas can you please share a reproducable example?

**Comment by Renkas** [comment] 2023-05-21 17:38
I believe I just did in the last post.

Anyway I removed inlang and went with typesafe i18n instead as it seems to be way too early to adopt it in production with all the issues I have stumbled upon. And I really don't have time or qualifications to debug and find workarounds for all of them.

Will try inlang again in a future project.

**Comment by samuelstroschein** [comment] 2023-05-21 18:02
@Renkas You can use typesafe-i18n with inlang! :) A typesafe-i18n plugin exists https://github.com/ivanhofer/inlang-plugin-typesafe-i18n.  

PS We should mention that the SDK is alpha! We mentioned it during the svelte summit but I guess it is unclear when skimming over the docs.

**Comment by Devidence7** [comment] 2023-05-22 21:34
Thank you for addressing the issue. I have tested the latest release (version 0.6.0) and I am pleased to confirm that the bug has been successfully resolved in my case. The nested styles now function as expected without triggering any errors. Great work on the quick fix! 👍

**Closed** 2023-05-22 21:49 UTC
Labels: type: bug, scope: sdk-js

**Comment by ivanhofer** [comment] 2023-05-23 06:49
Thanks for the confirmation!
