### ISSUE TITLE
[bug] 502 if I try to generate a badge for cal.com

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#1190] opened 2023-07-31 08:42 UTC
### Problem

I tried to generate a badge for cal.com
The repo link is:
https://inlang.com/badge?url=github.com/calcom/cal.com

### Expected behavior
An image like this 
[![translation badge](https://inlang.com/badge?url=github.com/AppFlowy-IO/AppFlowy)](https://inlang.com/editor/github.com/AppFlowy-IO/AppFlowy?ref=badge)

### Reproduction

 click on https://inlang.com/badge?url=github.com/calcom/cal.com

### `inlang.config.js` file

```JavaScript
// see https://inlang.com/
export async function defineConfig(env) {

	const { default: i18nextPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@2/dist/index.js",
	)

  const { default: standardLintRules } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js",
	)

	return {
		referenceLanguage: "en",
		plugins: [
			i18nextPlugin({
				pathPattern: "./apps/web/public/static/locales/{language}/common.json",
			}),
      standardLintRules({
        // deactivating identical pattern because of nested
        // resources like "de-DE" and "de-AT" where "de-AT"
        // contrains overwrites but the majority are identical patterns. 
        identicalPattern: "off"
      }),
		],
	}
}
```

### Other information

I can imagin the problem is the repo name /calcom/cal.com and the badge generated/ domain can't handle the`.com`

**Comment by jannesblobel** [comment] 2023-07-31 12:22
@inlang/badge

**Comment by NiklasBuchfink** [comment] 2023-07-31 13:03
@jannesblobel We have had this before. The server crashes because Cal.com is too big for our server to handle. It's a "run out of memory error" when we open the repo locally. We take down our server for a short time when we request a Cal.com badge.

**Comment by jannesblobel** [comment] 2023-07-31 13:08
Ok in this case, shall we close this issue? as not planned? Otherwise, it looks like an " I am open for more than 1 year" Issue

**Comment by samuelstroschein** [comment] 2023-07-31 14:15
Hahaha looool now we know why inlang.com is sometimes down :D people are trying to generate badges taking all of inlang.com down

**Comment by samuelstroschein** [comment] 2023-07-31 14:15
Duplicate of #963

**Closed by samuelstroschein** 2023-07-31 14:15 UTC
Labels: type: bug
