### ISSUE TITLE
first loading  of Documentation page is too slow 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#237] opened 2022-12-30 13:00 UTC
## Problem
on the first loading, the docs page is clickable, but nothing happens. only After ca.3-4 sec the doc page ist loaded/ rendered 
## Steps to reproduce

1. open a new browser window/ incognito mode  '...'
2. go to  'inlang.com'
3. click on ' documentation'
4. waiting ......
### Expected behavior
Loading faster

**Comment by samuelstroschein** [comment] 2022-12-30 14:39
This issue occurs because the server creates an index on the first request of a documentation site.

https://github.com/inlang/inlang/blob/0bd056e41eb7fac81c17b14502de2193f2a940c1/source-code/website/src/pages/documentation/*/index.page.server.tsx#L35

The first request refers to the first request of a freshly booted server instance e.g. the first user that loads /documentation will have a longer loading time than every subsequent user after a server has been re-deployed.

A solution is to generate the index directly at boot time or somehow move the index generation into a build step. I couldn't find a quick solution for either. Since the issue is no bug and only effects the first user on a re-deploy, this won't be fixed for now.

**Closed by samuelstroschein** 2022-12-30 14:39 UTC
Labels: type: improvement
