### ISSUE TITLE
bug in roundtrip test 

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#626] opened 2023-05-03 07:52 UTC
## Problem
I wanted to ship a feature for the inlang-plugin-json (latest commit in this fork)
https://github.com/NilsJacobsen/inlang-plugin-json/tree/add-subpath-support

The roundtrip test seems not to work correctly.

### Expected behavior
The roundtrip test should work like this:
readResources -> AST (1) -> writeResources -> readResources -> AST (2).
AST (1) and AST (2) must be equal if the AST is not modified.

I discovered some issue in the stored value for AST (1). 
When the `roundtripTest` function gets called the AST (1) is provided as an argument. This AST (1) was created through the `readResource` function before calling the `roundTripTest`. 

```typescript
async function roundtripTest(config, resources) {
    const commonErrorMessage = "A roundtrip test of the readResources and writeResources functions failed:\n";
    console.log(resources[1].body)
    await config.writeResources({ config, resources });
    console.log(resources[1].body)
    const readResources = await config.readResources({ config });

    for (const resource of resources) {
        // check if the messages are identical
        for (const [messageIndex, message] of resource.body.entries()) {
            console.log(matchingReadResource.body[messageIndex])
            if (JSON.stringify(message) !== JSON.stringify(matchingReadResource.body[messageIndex]))
                throw new TestConfigException(dedent(`
                    ${commonErrorMessage}
                    The message with id "${message.id.name}" does not match for the resource 
                    with languageTag.name "${resource.languageTag.name}".

                    Received: 
                    ${JSON.stringify(message, undefined, 2)}

                    Expected:
                    ${JSON.stringify(matchingReadResource.body[messageIndex], undefined, 2)}
                `));
        }
    }
}
```

As you can see the resource is compared with the new readResources (AST (2)) to see if there is a match. What I discovered is that the AST(1) is not the same through the whole function. But since that is the reference AST(1) which is tested against there shouldn't be any kind of change in it. In this example I logged `console.log(resources[1].body)` before and after the `write` function. This function should only manipulate the files in the file system but not the resources. But after it get called we have some weird behavior that changes the ids of the AST(1) resource. 

## Steps to reproduce
In my fork you can get the same errors.

**Comment by NiklasBuchfink** [comment] 2023-05-10 10:40
I looked into it and experienced the same problems. It shouldn't be possible that the parameter `resources` of the function `roundtripTest` is different before and after the `writeResources` function.

So these logs should not differ from each other:
```js
async function roundtripTest(config, resources) {
    // ...
    console.log(resources[1].body)
    await config.writeResources({ config, resources });
    console.log(resources[1].body)
    // ...
```

@samuelstroschein Can you help us with this? We currently need this to support larger projects with a language folder structure.

**Note:** To see the logs, the logs needs to be added inside the `node_modules/@inlang/core/dist/test/testConfig.js`

Otherwise the extension seems to work, as the folder structure of `{language}/*.json` is resolved with `hallo.intro` for a message `intro` inside of the `hallo.json` file.

**Comment by samuelstroschein** [comment] 2023-05-10 16:15
The mutating resources where not a bug in the roundtrip test but the plugin that nils wrote. There was one minor bug was has been fixed though https://github.com/inlang/inlang/commit/925677188c10274db698719d1677fe09dfe2cb1f.

**Closed by samuelstroschein** 2023-05-10 16:15 UTC
Labels: type: bug, scope: core
