### ISSUE TITLE
"Get in touch" button does nothing

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#493] opened 2023-04-02 13:18 UTC
## Problem

![image](https://user-images.githubusercontent.com/21335119/229355263-28f752b1-8e57-46a6-b5fe-e97c32a69a58.png)

## Steps to reproduce

1. Go to https://inlang.com/
2. Click on "Get in touch"

### Expected behavior

Something should happen if the button get's clicked

**Comment by felixhaeberle** [comment] 2023-04-02 13:35
I think this is a false positive here? This should ideally open your preferred mail app. I can't reproduce it at least on mobile.

**Comment by NiklasBuchfink** [comment] 2023-04-02 14:47
No, there are actually two buttons for different screen sizes and one does not have a wrapping a-tag. Will be merged with the updates in the editor today.

**Closed** 2023-04-02 14:48 UTC
Labels: type: bug
