### ISSUE TITLE
runtime: 'edge' fails building SvelteKit

### ISSUE THREAD

**Issue by shinokada** [inlang/inlang#719] opened 2023-05-10 20:22 UTC
## Problem

Without `{ runtime: 'edge' }`, it builds without a problem. But when I add it, it fails.

```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-vercel';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [
		vitePreprocess(),
		preprocess({
			postcss: true
		})
	],

	kit: {
		adapter: adapter({ runtime: 'edge' }),
	}
};

export default config;
```

### Expected behavior

It should build without errors.

## Steps to reproduce

```
git clone git@github.com:shinokada/i18n-sveltekit-lib.git my-app
cd my-app
pnpm I
pnpm build
```
### Additional information (screenshots?)

<img width="1035" alt="image" src="https://github.com/inlang/inlang/assets/147320/844ad70e-27f1-49c6-92a1-a9397ce165be">

<img width="1032" alt="image" src="https://github.com/inlang/inlang/assets/147320/df118dde-2931-4088-9839-c287febe1466">

**Comment by ivanhofer** [comment] 2023-05-11 13:11
duplicate of #657

Version `0.4.2` fixes the issue

**Closed by ivanhofer** 2023-05-11 13:11 UTC
Labels: type: bug

**Comment by shinokada** [comment] 2023-05-11 20:56
Do I need to change the following inling.config.js?

```
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2.2.0/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.3.1/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
		],
	}
}
```

**Comment by ivanhofer** [comment] 2023-05-12 11:32
This is the page you are looking for: https://inlang.com/documentation/sdk/configuration
I will update it to also mention the `jsonPlugin` there.
