### ISSUE TITLE
[bug?] Inlang/i18next-plugin confuses nested keys with different files

### ISSUE THREAD

**Issue by dewil-official** [inlang/inlang#1134] opened 2023-07-19 08:37 UTC
### Problem

After resolving the issues that we had with invalid configuration, a user has made a [PR](https://github.com/remnoteio/translation/pull/7) using a fork through the Inlang Editor. But in the PR, instead of sticking to the configured file format (`./{language}/all.json`), it suddenly created a bunch of different files based on the top-level keys. It seems like it got confused with nested keys and is assuming that the top-level keys are namespaces instead, then creates the files accordingly.

I asked the user and they confirmed that they did not change this manually - the Inlang editor split the files like that. This is not desireable and violating the configured file format.

### Expected behavior

It should stick to the `./{language}/all.json` file structure and keep the nested translation keys intact, instead of splitting them out into different files.

### Reproduction

- Take [this PR](https://github.com/remnoteio/translation/pull/7/files) as a repro case.
- When changing only a single nested key, it does not happen (see [this example](https://github.com/remnoteio/translation/commit/16f8ef60ece34c8ee31835143eae883b45ac70b4))

From these cases, my assumption would be that it either only happens when changing multiple keys, or when the keys are nested deeper than 2 levels.

[This is our repo](https://github.com/remnoteio/translation)

### `inlang.config.js` file

```JavaScript
export async function defineConfig(env) {
  const { default: i18nextPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@3/dist/index.js"
  );

  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js"
  );

  return {
    referenceLanguage: "en",

    plugins: [
      i18nextPlugin({
        pathPattern: "./{language}/all.json",
      }),
      standardLintRules(),
    ],
  };
}
```

### `npx @inlang/cli config validate` file

```sh
❯ npx @inlang/cli config validate
error: unknown command 'validate'
```

### Other information

My assumption would be that the `i18next-plugin` interprets the nested translation keys as different namespaces. And when saving the changes, it tries to save them in different files.

Note I also had [this issue](https://github.com/inlang/inlang/issues/1132), I'd assume it's unrelated but just FYI.

**Comment by felixhaeberle** [comment] 2023-07-19 11:41
@dewil-official Can you execute `npx @inlang/cli@latest config validate` and post the output here? 
It seems the `config validate` command can't be found because of an outdated version of the CLI.

**Comment by NilsJacobsen** [comment] 2023-07-19 11:50
@dewil-official I tested the editor with a fresh fork and changed messages in German in common and template. 
See this fork -> https://github.com/NilsJacobsen/translation/commit/6b048933fcba2ef9f52b6f82c96a09eaf4c12048

It worked as intended.

**Comment by dewil-official** [comment] 2023-07-19 14:30
> Can you execute npx @inlang/cli@latest config validate and post the output here?
It seems the config validate command can't be found because of an outdated version of the CLI.

Sorry, I didn't realize from the output that it was requiring Node 18+. But when I tried to install the CLI globally again, it told me that and now I tried it in Node 18 successfully in that repo and here's the output:

```
translation on  main is 📦 v1.0.0 via  v18.17.0
❯ npx @inlang/cli config validate
i 🔎 Validating the config file...                                                                            16:20:38
√ 🎉 Inlang config is valid!
```

> I tested the editor with a fresh fork [...] It worked as intended.

Also tried some more things and couldn't repro it yet. Will report back here when I found a reliable method

**Comment by dewil-official** [comment] 2023-07-21 06:41
[The same user now made a new PR where the issue did not happen](https://github.com/remnoteio/translation/pull/9/files). Makes me think that either it is not an issue anymore, or this is very difficult to reproduce. In the original PR there have been more languages as well, maybe that's needed to repro it.

**Comment by NilsJacobsen** [comment] 2023-07-25 09:08
@dewil-official i'm gonna close this for now. Feel free to reopen if this should happen again.

**Closed by NilsJacobsen** 2023-07-25 09:08 UTC
Labels: type: bug
