### ISSUE TITLE
[bug] Build failing with JavaScript code

### ISSUE THREAD

**Issue by WarningImHack3r** [inlang/inlang#1197] opened 2023-08-01 20:00 UTC
### Problem

Sometimes (rarely), when running `vite build`, an error is instantly thrown from Inlang, displaying what looks like all the content of a minified JavaScript file, ending with this error:
```
Error: or]: fetch failed
    at Xu (file:///home/runner/work/Website/Website/node_modules/.pnpm/@inlang+sdk-js@0.7.1_@sveltejs+kit@1.22.4_esbuild@0.[18](https://github.com/EmeraldHQ/Website/actions/runs/5730982006/job/15530936917#step:7:19).17_svelte@4.1.2/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:166:[19](https://github.com/EmeraldHQ/Website/actions/runs/5730982006/job/15530936917#step:7:20)27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/Website/Website/node_modules/.pnpm/@inlang+sdk-js@0.7.1_@sveltejs+kit@1.22.4_esbuild@0.18.17_svelte@4.1.2/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:168:1431
```

> **Note**
> This might be already fixed in a more recent version than 0.7.1, however due to the #1195 I cannot upgrade yet

### Expected behavior

A cleaner error, not an entire nonsense JavaScript file, and potentially a fix to not making it ever happen (this seems to be a network/fetch issue, maybe retrying it or not making it blocking could be great)

### Reproduction

1. Run `vite build`
2. Randomly (but rarely) get this error

> **Note**
> As far as I remember, I seem to only ever have met this kind of error when running the build in a GitHub Actions

### `inlang.config.js` file

```JavaScript
/**
 * @type {import("@inlang/core/config").DefineConfig}
 */
export async function defineConfig(env) {
	const { default: pluginJson } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js"
	);

	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.7.1/dist/index.js"
	);

	const { default: standardLintRules } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js"
	);

	return {
		referenceLanguage: "en",
		plugins: [
			pluginJson({
				pathPattern: "./src/locales/{language}/*.json",
				variableReferencePattern: ["{", "}"]
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
			standardLintRules()
		]
	};
}
```

### `npx @inlang/cli@latest config validate` file

```sh
ℹ 🔎 Validating the config file...                                                                                                                           22:00:35
✔ 🎉 Inlang config is valid!                                                                                                                                 22:00:35
```

**Comment by ivanhofer** [comment] 2023-08-02 05:30
I can't reproduce the issue. Please share a repo with all the code we need to reproduce it.

**Comment by ivanhofer** [comment] 2023-08-03 06:45
When this happends the next time, could you please provide the lines of code that triggered the error?
I'll close this for now as we can't do anything without further details.

**Closed by ivanhofer** 2023-08-03 06:46 UTC
Labels: type: bug, scope: sdk-js

**Comment by WarningImHack3r** [comment] 2023-08-03 12:32
@ivanhofer Which lines of code? It happens during the `vite build`, I cannot be more precise, unfortunately...
It seems to be a downloading issue at the very beginning of the process, triggered by Inlang, that fails

In the first code snippet, I share there is the link to the full GitHub Actions run I experienced this in if you want. Let me know if you want me to restart it with debug enabled, though the issue may not appear on rerunning.

**Comment by ivanhofer** [comment] 2023-08-04 04:38
I have missed the actual reference to the SDK code in the stack track before. I took another look and fond it :)
Let's see if this error pops up again in the future.

**Comment by WarningImHack3r** [comment] 2023-08-04 10:48
What do you mean by "in the future"? On my repo? Should I keep that lower version?

**Comment by ivanhofer** [comment] 2023-08-04 13:02
No, please upgrade and let us know if you still encounter the issue :)
